### ISSUE TITLE
[feature] remove copied files

### ISSUE THREAD

**Issue by lnicola** [tarka/xcp#11]
Merry Christmas, first of all!

How would you feel about a feature to remove copied files? Alternatively (or, even better, in addition) `xcp` could support running an external command after one or more files have been copied.

**Comment by tarka** [comment]
I'm not averse to it, but it it would need to handle the (I assume) most common case of moving files within the same filesystem. In this case the fastest and safest method of doing this is to move the file's inode (which is what `mv` does in this case), which limits most of the advantage of `xcp`'s optimisations. I'd certainly look at patches though.

I'm not sure about running a secondary command; it's an interesting idea, but I think most cases where it would be used would be better handled by a higher level script. I'm happy to be proved wrong though.
