### ISSUE TITLE
Faulty detection of sparse files?

### ISSUE THREAD

**Issue by takluyver** [tarka/xcp#19]
The core of the detection of sparse files is:

https://github.com/tarka/xcp/blob/ea28a4dbec5a9f43210fe72b5c6f827eba9bbaf6/src/os/linux.rs#L182

I may be wrong, but I think the use of `st_blksize` here is a mistake.

`man 2 stat` describes `st_blksize` as 'the "preferred" block size for efficient filesystem I/O.', and `st_blocks` as 'the number of blocks allocated to the file, in 512-byte units.' I checked with Rust code on a regular (non-sparse) file:

```
[src/main.rs:7] meta.st_blksize() = 4096
[src/main.rs:8] meta.st_blocks() = 1512
[src/main.rs:9] meta.st_size() = 771765
[src/main.rs:10] meta.st_size() / meta.st_blksize() = 188
[src/main.rs:11] meta.st_size() / 512 = 1507
```

I think [these lines](https://github.com/coreutils/coreutils/blob/00ea4bacf6063ccc125209d5186f8f2382c6f0d4/src/copy.c#L1236-L1238) are the corresponding code in GNU cp. They use a constant `ST_NBLOCKSIZE` (from [this header file](https://github.com/coreutils/gnulib/blob/master/lib/stat-size.h)) rather than anything from the stat struct.

If so, the impact is probably minor - I think `st_blksize` is only likely to be bigger than 512, so it should never erroneously decide that a dense file is sparse. And it can still detect very sparse files (on my system, where holes are 7/8 of the total size), where it's likely to be most important to optimise copying. But it looks like it will miss other sparse files.

**Comment by tarka** [comment]
Sorry for taking so long to get to this. You are 100% correct. Fixed in 0.12.2.
