### ISSUE TITLE
File content is gone after copying it to itself

### ISSUE THREAD

**Issue by mariocynicys** [tarka/xcp#36]
Repro:
- Create a file `f1` with some arbitrary content.
- do `xcp f1 f1`
- The file content is now garbage

How do I get my file back. I am sorry I shouldn't have done that :sob:

**Comment by tarka** [comment]
I'm sorry, I'm not sure if you can recover a file in that scenario.

Really we should be performing a check in this case (or possibly setting `--noclobber` by default). I'll add a fix ASAP.

**Comment by tarka** [comment]
xcp 0.10.0 is out with a guard for this specific issue.
