### ISSUE TITLE
Clarify differences with cp

### ISSUE THREAD

**Issue by desbma** [tarka/xcp#4]
> xcp is a (partial) clone of the Unix cp command. It is not intended as a full replacement, but as a companion utility

I think you should clarify even further where `xcp` stands compared to coreutil's `cp`:
* either state that the behavior of `xcp` is close to the one of `cp`, so mention what specific `cp` options or features are not supported for example. The idea is that users that do not use theses options can safely do `alias cp=xcp` in their interactive shell, and benefit from the progressbar and speedup.
or 
* state that any form of compatibility with `cp` is not a goal, or even an inspiration

**Comment by tarka** [comment]
Fair point. I'm currently refactoring xcp to better support parallelism, which will require expanding the documentation, so I'll look at this then.

**Comment by tarka** [comment]
xcp does currently preserve some attributes, including permissions and xattrs. There are others we don't ATM, but probably should (timestamps and ownership-when-root). There are other `cp` options we may decide not to support (e.g. non-numbered-backups).

Basically I'm slowly going through and duplicating features from `cp` where it seems appropriate. Once that's done I'll write up where xcp differs significantly.

**Comment by ristomatti** [comment]
Ack. With a few exceptions the times I need to copy either big files or lots of files, they tend to be media files. I definitely want to preserve timestamps of media files. Hopefully this will be added at some point!

**Comment by tarka** [comment]
Yeah, the timestamps thing is a straight-up oversight on my part. It'll be fixed in the next release.

**Comment by tarka** [comment]
Timestamp copy is now in version 0.20.0. Note that this is enabled by default, which is a difference from `cp`.

**Comment by tarka** [comment]
See also #50.

**Comment by tarka** [comment]
The README has been updated with notes on `cp` differences.
