### ISSUE TITLE
Can xcp keep file uid/gid?

### ISSUE THREAD

**Issue by plusls** [tarka/xcp#55]
Can xcp keep linux file uid/gid?

**Comment by tarka** [comment]
Not currently, but it could be added. Presumably you mean when running as root? Usually it is not possible to copy UID/GID from a different user unless you are running as root (or have and equivalent capability/acl).

**Comment by plusls** [comment]
> Not currently, but it could be added. Presumably you mean when running as root? Usually it is not possible to copy UID/GID from a different user unless you are running as root (or have and equivalent capability/acl).

I just want to backup files with user permission and extra ACL attr.

**Comment by tarka** [comment]
Added `--ownership` flag in v0.22.0.
