### ISSUE TITLE
Consider putting the operations in their own library crate

### ISSUE THREAD

**Issue by nox** [tarka/xcp#8]

**Comment by tarka** [comment]
I'm open to this, especially some of the utility operations that may be useful elsewhere. Currently I'm doing a long refactor to support more fine-grained parallelism, which means I'm rewriting this code a lot. I'll revisit once it's stabilised.

**Comment by tarka** [comment]
Low-level sparse file handling and related operations have been published as [libfs](https://crates.io/crates/libfs)
